### ISSUE TITLE
Implement new dacade challenges design

### ISSUE THREAD

**Issue by moritzfelipe** [dacadeorg/dacade-webapp#202]
Changes in community: https://www.figma.com/file/6Hq5cBH6doeIrspVLzDyQt/Dacade?node-id=14897-17514&t=jwmYgOkX8eNqJCmp-0

Changes in course: https://www.figma.com/file/6Hq5cBH6doeIrspVLzDyQt/Dacade?node-id=15229-26095&t=jwmYgOkX8eNqJCmp-0

Changes in challenge: https://www.figma.com/file/6Hq5cBH6doeIrspVLzDyQt/Dacade?type=design&node-id=15621-20869&t=aYKapJlztufCq2b6-0

**Comment by nathaniawong** [comment]
@musayann to review https://github.com/dacadeorg/dacade-webapp/pull/267

**Comment by nathaniawong** [comment]
@karemarsy to resolve comments on #267

**Comment by nathaniawong** [comment]
@karemarsy working on challenge. @musayann to review #267 #269

**Comment by nathaniawong** [comment]
community: https://github.com/dacadeorg/dacade-webapp/pull/267
course: https://github.com/dacadeorg/dacade-webapp/pull/269
challenge: https://github.com/dacadeorg/dacade-webapp/pull/271
other prs: https://github.com/dacadeorg/dacade-frontend-app/pull/494 https://github.com/dacadeorg/dacade-frontend-app/pull/500

**Comment by nathaniawong** [comment]
@musayann needs to review all:

- [ ] community: https://github.com/dacadeorg/dacade-webapp/pull/267
- [ ] course: https://github.com/dacadeorg/dacade-webapp/pull/269
- [ ] challenge: https://github.com/dacadeorg/dacade-webapp/pull/271
- [ ] frontend: https://github.com/dacadeorg/dacade-frontend-app/pull/494 
- [ ] frontend: https://github.com/dacadeorg/dacade-frontend-app/pull/500

**Comment by nathaniawong** [comment]
@Jonath-z reviewing the PRs now

**Comment by nathaniawong** [comment]
Merged
